### ISSUE TITLE
Create an endif prefix

### ISSUE THREAD

**Issue by marcosjaski** [luwenjiechn/nunjucks-vscode-snippets#3]
I can see the plugin has the prefixes: if, ife, ifel, elif, else, but don't have an endif prefix.
I'm using the plugin for a while, it really helps to improve the productivity, but I miss an endif prefix.
Can you add this prefix, please?

**Comment by ilwk** [comment]
> I can see the plugin has the prefixes: if, ife, ifel, elif, else, but don't have an endif prefix. I'm using the plugin for a while, it really helps to improve the productivity, but I miss an endif prefix. Can you add this prefix, please?

Added，you can upgrade it
